// Posts helpers

export const ACTIONS = {
  GET_POSTS: "GET_POSTS",
  GET_POST_DETAILS: "GET_POST_DETAILS",
  GET_COMMENTS: "GET_COMMETNS",
  GET_RATING: "GET_RATING",
  GET_SELECTED: "GET_SELECTED",
};

export const POSTS_API = "http://localhost:8000/posts";

// Auth helpers

export const AUTH_ACTIONS = {
  GET_USER: "GET_USER",
  GET_CURRENT_USER: "GET_CURRENT_USER",
  GET_EMAIL: "GET_EMAIL",
  GET_PASSWORD: "GET_PASSWORD",
  GET_EMAIL_ERROR: "GET_EMAIL_ERROR",
  GET_PASSWORD_ERROR: "GET_PASSWORD_ERROR",
  GET_HAS_ACCOUNT: "GET_HAS_ACCOUNT",
  GET_DISPLAY_NAME: "GET_DISPLAY_NAME",
  GET_PHOTO_URL: "GET_PHOTO_URL",
  GET_OLD_PASSWORD: "GET_OLD_PASSWORD",
};
